# Generated by Django 5.2 on 2025-04-13 13:19

import apps.common.mixins.translated_slug
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('slug_fa', models.SlugField(null=True, unique=True, verbose_name='Slug')),
                ('slug_en', models.SlugField(null=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Used to build category URL.', max_length=200, unique=True, verbose_name='Slug')),
                ('slug_fa', models.SlugField(help_text='Used to build category URL.', max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('slug_en', models.SlugField(help_text='Used to build category URL.', max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='posts.category', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Used in the URL of the post.', unique=True)),
                ('slug_fa', models.SlugField(blank=True, help_text='Used in the URL of the post.', null=True, unique=True)),
                ('slug_en', models.SlugField(blank=True, help_text='Used in the URL of the post.', null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('hidden', 'Hidden'), ('published', 'published')], default='draft', max_length=10, verbose_name='Status')),
                ('publication_date', models.DateTimeField(blank=True, null=True, verbose_name='Publication Date')),
                ('start_publication', models.DateTimeField(blank=True, null=True, verbose_name='Start publication')),
                ('end_publication', models.DateTimeField(blank=True, null=True, verbose_name='End publication')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('summary_fa', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('summary_en', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_fa', models.TextField(null=True, verbose_name='Content')),
                ('content_en', models.TextField(null=True, verbose_name='Content')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.category', verbose_name='Category')),
                ('tags', models.ManyToManyField(blank=True, to='posts.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
            bases=(apps.common.mixins.translated_slug.TranslatedSlugMixin, models.Model),
        ),
    ]
