# Generated by Django 5.2 on 2025-04-16 12:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Used in the URL of the post.', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Used in the URL of the post.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Used in the URL of the post.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Summary'),
        ),
    ]
