# Generated by Django 5.2 on 2025-04-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_content_alter_post_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Used to build category URL.', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Used to build category URL.', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Used to build category URL.', null=True, unique=True, verbose_name='Slug'),
        ),
    ]
