# Generated by Django 5.2 on 2025-04-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_category_slug_alter_category_slug_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='toc',
            field=models.JSONField(blank=True, null=True, verbose_name='Table of content'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Used to build category URL.', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Used to build category URL.', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Used to build category URL.', null=True, unique=True, verbose_name='Slug'),
        ),
    ]
