# Generated by Django 5.2 on 2025-04-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='Used in the URL of the post.', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, help_text='Used in the URL of the post.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, help_text='Used in the URL of the post.', null=True, unique=True),
        ),
    ]
