# docker-compose.yml

version: '3.9'

services:
  web:
    build: .
    image: yadlog-backend:web-dev
    container_name: yadlog_web_dev
    command: bash /app/scripts/entrypoint.sh
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: yadlog_postgres_dev
    restart: always
    volumes:
      - yadlog_postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  yadlog_postgres_data: